// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkFDSKQGyzLB5dcqZ_FF3mYDaG5tmgnqw',
    appId: '1:307041645153:web:98b329eed84566d7c87020',
    messagingSenderId: '307041645153',
    projectId: 'community-deals',
    authDomain: 'community-deals.firebaseapp.com',
    storageBucket: 'community-deals.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFcTaAvFJ9JGCheZhYSnflxri4wkCxBWg',
    appId: '1:307041645153:android:1cd2bbfceb824ab2c87020',
    messagingSenderId: '307041645153',
    projectId: 'community-deals',
    storageBucket: 'community-deals.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCK_WP4hv9ZPMOYGaDnFhQhBlfKEk0IYuM',
    appId: '1:307041645153:ios:7fdb31bb43c48201c87020',
    messagingSenderId: '307041645153',
    projectId: 'community-deals',
    storageBucket: 'community-deals.appspot.com',
    iosClientId: '307041645153-rsn51q3obiu71aqqft2s4b1psb5cbk9u.apps.googleusercontent.com',
    iosBundleId: 'com.example.hackutd9',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCK_WP4hv9ZPMOYGaDnFhQhBlfKEk0IYuM',
    appId: '1:307041645153:ios:7fdb31bb43c48201c87020',
    messagingSenderId: '307041645153',
    projectId: 'community-deals',
    storageBucket: 'community-deals.appspot.com',
    iosClientId: '307041645153-rsn51q3obiu71aqqft2s4b1psb5cbk9u.apps.googleusercontent.com',
    iosBundleId: 'com.example.hackutd9',
  );
}
